AllCops:
  Exclude:
    - gems/**/*
    - test/chef_cookbook/**/*
    - drone-chef.gemspec

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
